version: '3.4'

services:
  microservicedemo.api.blog:
    image: ${DOCKER_REGISTRY-}microservicedemoapiblog
    build:
      context: .
      dockerfile: MicroServiceDemo.Api.Blog/Dockerfile
    ports:
      - "5001:80"

  microservicedemo.api.comments:
    image: ${DOCKER_REGISTRY-}microservicedemoapicomments
    build:
      context: .
      dockerfile: MicroServiceDemo.Api.Comments/Dockerfile
    ports:
      - "5002:80"

  microservicedemo.api.auth:
    image: ${DOCKER_REGISTRY-}microservicedemoapiauth
    build:
      context: .
      dockerfile: MicroServiceDemo.Api.Auth/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_RabbitMq__HostName=rabbitmq
    ports:
      - "5003:80"

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zvInGu5iJlSNIRWEDRu1"
      ACCEPT_EULA: "Y"
    ports:
      - "14433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq